services:
  web:
    build: .
    ports:
      - "8034:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data_todoapi:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tododb

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./docker/support/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  postgres_data_todoapi:
